In [1]:
import numpy as np

In [40]:
def load_data(filename, path='D:/Downloads/Category and Attribute Prediction/Anno_fine/'):
    f = open(path + filename)
    lines = f.readlines()
    attr = []
    for i in lines:
        attr.append([int(x) for x in i.split()])
        
    return np.array(attr, dtype = int)

In [41]:
def load_attr(filename, path='D:/Downloads/Category and Attribute Prediction/Anno_fine/'):
    f = open(path + filename)
    lines = f.readlines()
    attr_list = []
    for i in lines[2:]:
        attr_list.append(i.split()[0])
    
    return attr_list

In [77]:
def load_cat_data(filename, path='D:/Downloads/Category and Attribute Prediction/Anno_fine/'):
    f = open(path + filename)
    lines = f.readlines()
    attr = np.zeros(len(cat_list), dtype=int)
    for i in lines:
        attr[int(i)] += 1
    return attr

In [102]:
attr_list = load_attr('list_attr_cloth_ko.txt')

In [87]:
train_attr = load_data('train_attr.txt')

In [88]:
val_attr = load_data('val_attr.txt')

In [89]:
test_attr = load_data('test_attr.txt')

In [90]:
np.sum(np.array([sum(train_attr),sum(val_attr),sum(test_attr)]),axis=1)

array([84000, 12000, 24000])

In [91]:
np.sum(np.sum(np.array([sum(train_attr),sum(val_attr),sum(test_attr)]),axis=1))

120000

In [105]:
attr_list

['꽃무늬',
 '그래픽',
 '줄무늬',
 '자수를',
 '주름',
 '솔리드',
 '격자무늬',
 '긴소매',
 '반소매',
 '민소매',
 '롱드레스',
 '미니드레스',
 '상/하의',
 '크루넥',
 '브이넥',
 '스퀘어넥',
 '목선',
 '데님',
 '쉬폰',
 '면',
 '가죽',
 '가짜',
 '니트',
 '타이트한',
 '널널한',
 '평범한']

In [106]:
pd.DataFrame(index=attr_list, data=np.array([sum(train_attr),sum(val_attr),sum(test_attr)]).T, columns=['train_count','val_count','test_count'])

       train_count  val_count  test_count
꽃무늬           2383        355         664
그래픽           2329        349         668
줄무늬            938        117         292
자수를           1179        150         338
주름             296         40          78
솔리드           6633        951        1898
격자무늬           242         38          62
긴소매           4269        605        1243
반소매           2437        351         686
민소매           7294       1044        2071
롱드레스          1436        205         388
미니드레스         2706        398         730
상/하의          9858       1397        2882
크루넥           5679        771        1636
브이넥           2416        374         668
스퀘어넥            47          4          10
목선            5858        851        1686
데님             835        114         245
쉬폰            2073        269         543
면             9469       1399        2736
가죽             292         38          76
가짜             124         19          46
니트            1207        161         354
타이트한          2001        295         595
널널한            758        110         201
평범한          11241       1595        3204

In [164]:
cat_list_ko = load_attr('list_category_cloth_ko.txt')

In [159]:
cat_list = load_attr('list_category_cloth.txt')

In [94]:
train_cat = load_cat_data('train_cate.txt')

In [95]:
val_cat = load_cat_data('val_cate.txt')

In [96]:
test_cat = load_cat_data('test_cate.txt')

In [97]:
len(cat_list),train_cat.shape, val_cat.shape, test_cat.shape

(50, (50,), (50,), (50,))

In [98]:
pd.DataFrame(index=cat_list, data=np.array([train_cat,val_cat,test_cat]).T, columns=['train_count','val_count','test_count'])

       train_count  val_count  test_count
아노락              0          0           0
블레이저             9          1           3
블라우스           367         53         112
봄버            1055        156         297
버튼              16          3           4
가디건              9          0           1
플란넬            635         85         198
홀터넥              6          0           7
헨리넥              1          0           0
후드              45          8          13
자켓             201         24          64
저지             476         60         137
파카              40          4          14
피코트             26          5           9
판초               2          1           1
스웨터             35          9          12
탱크             557         75         168
티셔츠            726        105         210
상의            1621        213         455
터틀넥            534         75         166
7부              11          1           2
치노               7          0           1
팬티              28          5          12
컷오프             34          3           4
가우초             71         10          15
청바지              0          0           0
제깅스            344         53         105
승마용             29          3          16
조거               3          0           3
레깅스            200         24          70
사롱             232         32          67
반바지              3          0           0
치마             822        118         220
추리닝            680        112         215
트레이닝복          116         17          29
트렁크             58         11          14
카프탄             17          4           8
케이프              1          0           0
코트               0          0           0
커버업            115         17          25
원피스              2          0           0
점프수트          4016        589        1064
카프탄            351         47         105
기모노              8          0           1
잠옷             143         21          36
원지               0          0           0
로브               5          0           2
롬퍼               3          2           2
셔츠             340         54         113
여름용              0          0           0

In [143]:
def make_label_file(img_file, bbox, cate, attr, path='D:/Downloads/Category and Attribute Prediction/Anno_fine/',):
    imgs = open(path + img_file).read().splitlines()
    bboxs = open(path + bbox).read().splitlines()
    cates = open(path + cate).read().splitlines()
    attrs = open(path + attr).read().splitlines()
    
    d = list()
    
    for i in range(len(imgs)):
        d.append(f'{imgs[i]} {bboxs[i]} {cates[i]} {attrs[i]}')
        
    with open('merged_'+img_file,'w') as f:
        for item in d:
            f.write('%s\n' % item)

In [144]:
make_label_file('train.txt','train_bbox.txt','train_cate.txt','train_attr.txt')

In [146]:
make_label_file('val.txt','val_bbox.txt','val_cate.txt','val_attr.txt')

In [146]:
make_label_file('test.txt','test_bbox.txt','test_cate.txt','test_attr.txt')

In [147]:
data = open('merged_train.txt', 'r').read().splitlines()

In [153]:
line = data[0]
ss = line.split()

In [154]:
for i in range(len(ss)):
    print(ss[i])

img/Sweet_Crochet_Blouse/img_00000070.jpg
066
075
241
293
3
0
0
0
1
0
0
0
0
0
1
0
0
1
0
0
0
1
0
1
0
0
0
0
0
0
1

In [161]:
d = dict()

In [162]:
for i in cat_list:
    d[i] = len(d)

In [163]:
d

{'Anorak': 0,
 'Blazer': 1,
 'Blouse': 2,
 'Bomber': 3,
 'Button-Down': 4,
 'Cardigan': 5,
 'Flannel': 6,
 'Halter': 7,
 'Henley': 8,
 'Hoodie': 9,
 'Jacket': 10,
 'Jersey': 11,
 'Parka': 12,
 'Peacoat': 13,
 'Poncho': 14,
 'Sweater': 15,
 'Tank': 16,
 'Tee': 17,
 'Top': 18,
 'Turtleneck': 19,
 'Capris': 20,
 'Chinos': 21,
 'Culottes': 22,
 'Cutoffs': 23,
 'Gauchos': 24,
 'Jeans': 25,
 'Jeggings': 26,
 'Jodhpurs': 27,
 'Joggers': 28,
 'Leggings': 29,
 'Sarong': 30,
 'Shorts': 31,
 'Skirt': 32,
 'Sweatpants': 33,
 'Sweatshorts': 34,
 'Trunks': 35,
 'Caftan': 36,
 'Cape': 37,
 'Coat': 38,
 'Coverup': 39,
 'Dress': 40,
 'Jumpsuit': 41,
 'Kaftan': 42,
 'Kimono': 43,
 'Nightdress': 44,
 'Onesie': 45,
 'Robe': 46,
 'Romper': 47,
 'Shirtdress': 48,
 'Sundress': 49}

In [172]:
d2 = dict()
cnt=0
for i in cat_list_ko:
    d2[i]=cnt
    cnt+=1

In [173]:
d2

{'아노락': 0,
 '블레이저': 1,
 '블라우스': 2,
 '봄버': 3,
 '버튼': 4,
 '가디건': 5,
 '플란넬': 6,
 '홀터넥': 7,
 '헨리넥': 8,
 '후드': 9,
 '자켓': 10,
 '저지': 11,
 '파카': 12,
 '피코트': 13,
 '판초': 14,
 '스웨터': 15,
 '탱크': 16,
 '티셔츠': 17,
 '상의': 18,
 '터틀넥': 19,
 '7부': 20,
 '치노': 21,
 '팬티': 22,
 '컷오프': 23,
 '가우초': 24,
 '청바지': 25,
 '제깅스': 26,
 '승마용': 27,
 '조거': 28,
 '레깅스': 29,
 '사롱': 30,
 '반바지': 31,
 '치마': 32,
 '추리닝': 33,
 '트레이닝복': 34,
 '트렁크': 35,
 '카프탄': 42,
 '케이프': 37,
 '코트': 38,
 '커버업': 39,
 '원피스': 40,
 '점프수트': 41,
 '기모노': 43,
 '잠옷': 44,
 '원지': 45,
 '로브': 46,
 '롬퍼': 47,
 '셔츠': 48,
 '여름용': 49}

In [169]:
len(cat_list_ko)

50